### PR TITLE
Fix client trying EPSV for every request on servers that do not support EPSV

### PR DESCRIPTION
**Pull request by duke-4**

### CODE REVIEW

**Comment by muirmanders** [comment]
I don't think we can add this check because not all EPSV capable servers indicate EPSV in their FEAT keywords. An IPv6 client would not be able to transfer files with a server that doesn't advertise EPSV if we made this change.

[RFC 2428](https://tools.ietf.org/html/rfc2428) does not specify a feature keyword to identify servers that support this functionality.  [RFC 5795](https://tools.ietf.org/html/rfc5797) suggests "nat6", but this standard is too new. Some servers do use "EPSV", but some use "nat6" and others don't indicate support of EPSV at all.

**Comment by duke-4** [comment]
Okay, I changed the code to remember the state for each connection.

**Comment by muirmanders** [comment]
So I'm clear on the motivation for this change, what is the problem with trying EPSV every time?

**Comment by duke-4** [comment]
If you are downloading alot of small files over a connection with high ping to the target ftp (that does not support EPSV) it slows down the overall process of downloading. For every other file there will be an obsolete EPSV command that will fail.

**Comment by muirmanders** [comment]
Thanks, that makes sense. Can you please remove commit cef05f41b56daac0e0f545bcc06e15d741ef5912 and add your above reasoning to the commit message for d14c34ffd24654de97e1a24b5e2ca6bdd64e3f22? You can force push your same branch, or make a new branch, whichever you prefer.

**Pull request closed without merging**
