### PR TITLE
Add RetrievePartial method to allow resume of a partially transferred file

### PR DESCRIPTION
**Pull request by gm42**
* Add RetrievePartial method to allow resume of a partially transferred file

**NOTE:** I did not add any test for this new method.

### CODE REVIEW

**Comment by muirmanders** [comment]
Thank you. Can you describe the use case for this method? I am tentative to add additional methods to the API to keep as it 1-to-1 w/ the ftp commands as I can.

**Comment by gm42** [comment]
@muirmanders sure. This is used in case you have a file partially downloaded (imagine network connection being interrupted in a previous download attempt), and you want to continue the download from a specific offset.

It exposes `transferFromOffset`, which uses internally the FTP `REST` command. Rather than exposing the `REST` API directly, I thought that exposing the functionality as in this PR is more apt.

**Comment by muirmanders** [comment]
I'm trying to keep the API simple, so I don't think this feature warrants its own method.

One other possibility is to make `Retrieve` check if the `io.Writer` is an `io.Seeker`, and if so "resume" the download based on the current offset. This way if you wanted to resume a previous download attempt, you could seek your *os.File to the end and then invoke `Retrieve`.

**Comment by gm42** [comment]
That is an implicit behavior, unless you make the type explicitly `io.SeekerWriter`. In both cases (checking at run-time if the interface `io.Seeker` is satisfied or explicitly using `io.SeekerWriter`) you would make a compromise.

I retire the PR, thanks for your feedback.

**Pull request closed without merging**
